import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata = {
    title: "eSRL – Studying gamified",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
                <Toaster
                    position="top-center"
                    toastOptions={{
                        error: {
                            style: {
                                background: "#FF3B3F", // 👈 your color
                                color: "#fff",
                            },
                        },
                        success: {
                            style: {
                                background: "#00A03B", // 👈 your color 5AB669
                                color: "#fff",
                            },
                        },
                    }}
                />
            </body>
        </html>
    )
}
